config:
  name: last
  process:
  - datasets:
    - cache_latents_to_disk: true
      caption_ext: txt
      folder_path: /dataset/images/1887298a-dea2-47e2-b8bb-b315bd5d32fa/img
      is_reg: false
      resolution:
      - 512
      - 768
      - 1024
    device: cuda
    model:
      arch: qwen_image
      low_vram: true
      name_or_path: /cache/models/gradients-io-tournaments--Qwen-Image-Jib-Mix
      qtype: float8
      quantize: true
      quantize_te: true
    network:
      linear: 128
      linear_alpha: 128
      type: lora
    save:
      dtype: bf16
      max_step_saves_to_keep: 4
      save_every: 250
      save_format: diffusers
    train:
      batch_size: 1
      cache_text_embeddings: true
      cfg_scale: 6.0
      do_cfg: true
      dtype: bf16
      ema_config:
        ema_decay: 0.995
        use_ema: true
      gradient_accumulation: 1
      gradient_checkpointing: true
      lr: 0.0001
      noise_scheduler: flowmatch
      optimizer: adamw8bit
      optimizer_params:
        weight_decay: 1.0e-05
      steps: 2500
      timestep_type: weighted
      train_text_encoder: false
      train_unet: true
    training_folder: /app/checkpoints/1887298a-dea2-47e2-b8bb-b315bd5d32fa/tournament-tourn_c43e1fc22c71be8f_20260618-1887298a-dea2-47e2-b8bb-b315bd5d32fa-5GU4Xkd3
    type: diffusion_trainer
job: extension
meta:
  name: qwen_image_lora
  version: '1.0'
