config:
  name: last
  process:
  - datasets:
    - cache_latents_to_disk: true
      caption_ext: txt
      folder_path: /dataset/images/956b14d3-7c4d-4d1a-8614-19d6bd025b2f/img
      is_reg: false
      resolution:
      - 512
      - 768
      - 1024
    device: cuda
    model:
      arch: zimage:turbo
      assistant_lora_path: /cache/hf_cache/zimage_turbo_training_adapter_v2.safetensors
      name_or_path: /cache/models/gradients-io-tournaments--Z-Image-Turbo
      qtype: qfloat8
      qtype_te: qfloat8
      quantize: true
      quantize_te: true
    network:
      conv: 16
      conv_alpha: 16
      linear: 32
      linear_alpha: 32
      type: lora
    save:
      dtype: bf16
      max_step_saves_to_keep: 4
      save_every: 250
      save_format: diffusers
    train:
      batch_size: 1
      dtype: bf16
      gradient_checkpointing: true
      lr: 0.0001
      noise_scheduler: flowmatch
      optimizer: adamw8bit
      steps: 168
      timestep_type: weighted
    training_folder: /app/checkpoints/956b14d3-7c4d-4d1a-8614-19d6bd025b2f/tournament-tourn_c43e1fc22c71be8f_20260618-956b14d3-7c4d-4d1a-8614-19d6bd025b2f-5FW2Eaae
    trigger_word: Evelyn Reed
    type: diffusion_trainer
job: extension
meta:
  name: zimage_lora
  version: '1.0'
