no_metadata = true
async_upload = false
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
dynamo_backend = "no"
enable_bucket = true
gradient_checkpointing = true
low_vram = false
max_bucket_reso = 2048
max_data_loader_n_workers = 4
max_grad_norm = 1
max_token_length = 75
min_bucket_reso = 256
mixed_precision = "bf16"
no_half_vae = true
output_dir = "/work/out"
output_name = "last"
pretrained_model_name_or_path = "/work/base"
prior_loss_weight = 1
resolution = "1024,1024"
sample_prompts = ""
sample_sampler = "euler_a"
save_model_as = "safetensors"
save_precision = "bf16"
full_fp16 = false
train_data_dir = "/work/img"
training_comment = ""
xformers = true
loss_type = "l2"
train_batch_size = 8
gradient_accumulation_steps = 1
optimizer_type = "prodigy"
optimizer_args = ["decouple=True", "d_coef=1.1", "weight_decay=0.01", "use_bias_correction=True", "safeguard_warmup=True"]
unet_lr = 0.95
text_encoder_lr = 0.95
lr_scheduler = "constant"
clip_skip = 1
max_timestep = 1000
min_snr_gamma = 6
scale_weight_norms = 5
caption_dropout_rate = 0
network_dropout = 0
seed = 2951032222
network_module = "lycoris.kohya"
network_dim = 32
network_alpha = 32
network_args = ["conv_dim=4", "conv_alpha=4", "algo=lora", "dora_wd=True", "dropout=0"]
max_train_epochs = 45
save_every_n_epochs = 5
